import Head from 'next/head';
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiOutlineDoubleRight,
  AiFillGithub,
  AiOutlineSend,
} from "react-icons/ai";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import html from "../public/html.png";
import css from "../public/css.png";
import js from "../public/js.png";
import react from "../public/react.png";
import redux from "../public/redux.png";
import tailwind from "../public/tailwind.png";
import github from "../public/github.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";



export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={ darkMode ? "dark" : ""}>
      <Head>
        <title>My Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-fakewhite px-10 md:px-20 lg:px-40 dark:bg-darkbg'>
        <section className=' min-h-screen'>
        <nav className='py-10 mb-12 flex justify-between '>
          <h1 className=' text-xl font-burtons dark:text-yellow-300'>Mon2.Dev</h1>
          <ul className='flex items-center'>
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/>
            </li>
            <li><a className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
          </ul>
        </nav>
        <div className='text-center  flex-col'>
          <h2 className='text-5xl py-2 text-lighttext font-burtons md:text-6xl   dark:text-white'>Montu Gohain</h2>
          <h3 className=' text-5xl mb-5 py-2 md:text-3xl dark:text-gray-300'>Frontend Web Deverloper</h3>  
        <a className=' bg-yellow-400 text-xl text-gray-800 rounded-md font-mono mt-5 mb-5 p-2' href="mailto:montugohaindb@gmail.com">Contact Me</a>

        </div>
        <div className='text-5xl mt-3 flex justify-center gap-16 py-3 text-gray-600'>


          <AiFillTwitterCircle />
          <AiFillLinkedin />
          <AiFillYoutube />
          <AiFillGithub />
        </div>
        <div className='mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96'>
            <Image src={deved} layout="fill" objectFit="cover" />
        </div>
        </section>
        {/* Second Section */}
        <section>
          <div>
            <h3 className=" text-center mb-10 text-5xl py-1  font-medium dark:text-fakewhite ">Skills and Tech-Stack</h3>
             
          </div>
          <div className="lg:flex gap-10 justify-center">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-cardlight dark:bg-fakewhite scale-75">

            
                 <Image src={html} width={100} height={100} layout="responsive" className=" "/>
    
              <h3 className="text-lg font-medium pt-8 pb-2 mt-10 ">
                <strong>HTML</strong>
              </h3>
            
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-cardlight dark:bg-fakewhite scale-75">

            
                 <Image src={css} width={100} height={100} layout="responsive"  className=" flex justify-center ml-2"/>
    
             
              <h3 className="text-lg font-medium pt-8 pb-2 mt-9">
                <strong>CSS</strong>
              </h3>
            
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-cardlight dark:bg-fakewhite scale-75">

            
                 <Image src={js} width={100} height={100} layout="responsive"  className=" flex justify-center ml-2"/>
    
             
              <h3 className="text-lg font-medium pt-8 pb-2 mt-10 ">
                <strong>JAVASCRIPT</strong>
              </h3>
            
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-cardlight dark:bg-fakewhite scale-75">

            
                 <Image src={react} width={100} height={100} layout="responsive" className=" flex justify-center ml-2"/>
    
             
              <h3 className="text-lg font-medium pt-8 pb-2 mt-10 ">
                  <strong>REACT</strong>
              </h3>
            
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-cardlight dark:bg-fakewhite scale-75">

            
                 <Image src={redux} width={100} height={100} layout="responsive" />
    
             
              <h3 className="text-lg font-medium mt-10 pt-6 ">
                <strong>REDUX</strong>
              </h3>
            
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-cardlight dark:bg-fakewhite scale-75">

            
                 <Image src={tailwind} width={100} height={100} layout="responsive" className=" flex justify-center ml-2"/>
    
             
              <h3 className="text-lg font-medium pt-10 mt-10 ">
                <strong>TAILWIND CSS</strong>
              </h3>
            
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-cardlight dark:bg-fakewhite scale-75">

            
                 <Image src={github} width={100} height={100}  layout="responsive" className=" flex  items-center "/>
    
             
              <h3 className="text-lg font-medium mt-24">
               <strong>GITHUB</strong> 
              </h3>
            </div>
           
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className=" bg-gd_text_r px-9 py-8 text-3xl  flex justify-between ">PROJECTS<AiOutlineDoubleRight/></h3> 
            <p className="text-md py-2 leading-8  dark:text-gray-200">
              From the begining of my college I was curious about web development.So, tried to make some realworld project or clones of existing websites to learn 
              about web development.My projects at a glace. </p> 
            
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                className=" scale-75 rounded-lg object-cover hover:opacity-30 transition duration-2500  ease-in hover:ease-in hover:scale-100 cursor-pointer"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}

                
              />
            
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className=" scale-75 rounded-lg object-cover hover:opacity-30 transition duration-2500  ease-in hover:ease-in hover:scale-100 cursor-pointer"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className=" scale-75 rounded-lg object-cover hover:opacity-30 transition duration-2500  ease-in hover:ease-in hover:scale-100 cursor-pointer"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className=" scale-75 rounded-lg object-cover hover:opacity-30 transition duration-2500  ease-in hover:ease-in hover:scale-100 cursor-pointer"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className=" scale-75 rounded-lg object-cover hover:opacity-30 transition duration-150 ease-out hover:ease-in hover:scale-100 cursor-pointer"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1 relative ">
            
              <a href="https://github.com/Montu-Gohain">
              <Image
                className="  scale-75 rounded-lg object-cover hover:opacity-30 transition duration-2500  ease-in hover:ease-in hover:scale-50 cursor-pointer"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
                
              />
              </a>
            </div>
          </div>

          <form action="https://formsubmit.co/montugohaindb@gmail.com" method="POST">

               <div className='bg-gray-900 w-auto h-auto py-10'>
                <hr className=' h-2 bg-gray-500 border-transparent'/>
                 <h1 className=' mt-4  text-center text-white text-5xl font-burtons'>CONTACT ME</h1>
                   <input placeholder='Name' type="text" className=' bg-gray-600 text-white flex justify-center ml-auto px-4 mr-auto mt-6 w-80 h-9 '/>
                   <input placeholder='Email' type="email" className=' bg-gray-600 text-white flex justify-center ml-auto px-4 mr-auto mt-6  w-80 h-9'/>
                    <textarea placeholder='Message' name="message" id="" cols="38" rows="10" className=' bg-gray-700 flex text-white px-3 justify-center w-auto mt-6 ml-auto mr-auto py-2' ></textarea>
                   <button className=' bg-amber-400 flex justify-center mt-6 ml-auto mr-auto w-60 text-darkbg py-2'><AiOutlineSend/></button>
               </div>
            </form>

        </section>

        {/* Let's create the contact us page */}

     

      </main>

    
    </div>
  );
}
